In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import BatchNormalization, LayerNormalization

np.random.seed(42)
tf.random.set_seed(42)



In [2]:
# Simulate a batch of 4 samples, each with 5 features
data = np.random.randint(1, 100, size=(4, 5)).astype(np.float32)

print("Original Input:\n", data)

Original Input:
 [[52. 93. 15. 72. 61.]
 [21. 83. 87. 75. 75.]
 [88. 24.  3. 22. 53.]
 [ 2. 88. 30. 38.  2.]]


In [3]:
batch_norm_layer = BatchNormalization()

# training=True so it normalizes using the current batch's mean/variance
batch_norm_output = batch_norm_layer(data, training=True)

print("Batch Normalization Output:\n", batch_norm_output.numpy())

Batch Normalization Output:
 [[ 0.34510362  0.7516792  -0.5823407   0.9000547   0.48072648]
 [-0.6058486   0.3937366   1.6538475   1.033396    0.98866415]
 [ 1.4494354  -1.7181242  -0.9550387  -1.3223026   0.19047654]
 [-1.1886903   0.5727079  -0.11646813 -0.61114824 -1.6598673 ]]


In [4]:
layer_norm_layer = LayerNormalization()

layer_norm_output = layer_norm_layer(data)

print("Layer Normalization Output:\n", layer_norm_output.numpy())

Layer Normalization Output:
 [[-0.25639224  1.3363471  -1.6937423   0.5205538   0.09323359]
 [-1.962309    0.61530066  0.78159785  0.28270578  0.28270578]
 [ 1.6851157  -0.4718324  -1.1795809  -0.539237    0.50553477]
 [-0.9509679   1.7751402  -0.06339788  0.19019353 -0.9509679 ]]


In [5]:
print("Original:\n", data)
print("\nAfter Batch Norm:\n", batch_norm_output.numpy())
print("\nAfter Layer Norm:\n", layer_norm_output.numpy())

Original:
 [[52. 93. 15. 72. 61.]
 [21. 83. 87. 75. 75.]
 [88. 24.  3. 22. 53.]
 [ 2. 88. 30. 38.  2.]]

After Batch Norm:
 [[ 0.34510362  0.7516792  -0.5823407   0.9000547   0.48072648]
 [-0.6058486   0.3937366   1.6538475   1.033396    0.98866415]
 [ 1.4494354  -1.7181242  -0.9550387  -1.3223026   0.19047654]
 [-1.1886903   0.5727079  -0.11646813 -0.61114824 -1.6598673 ]]

After Layer Norm:
 [[-0.25639224  1.3363471  -1.6937423   0.5205538   0.09323359]
 [-1.962309    0.61530066  0.78159785  0.28270578  0.28270578]
 [ 1.6851157  -0.4718324  -1.1795809  -0.539237    0.50553477]
 [-0.9509679   1.7751402  -0.06339788  0.19019353 -0.9509679 ]]


In [7]:
explanation = """
Batch Normalization normalizes each feature (column) across all samples in the batch,
using the mean and variance computed per feature over the batch dimension.

Layer Normalization normalizes each sample (row) independently, using the mean and
variance computed per sample across all its features.

Key difference: BatchNorm's statistics depend on other samples in the batch (so batch
size matters and it behaves differently at train vs inference time), while LayerNorm's
statistics depend only on the single sample itself - making it batch-size independent
and a common choice for RNNs/Transformers where batch statistics can be unstable.
"""

print(explanation)


Batch Normalization normalizes each feature (column) across all samples in the batch,
using the mean and variance computed per feature over the batch dimension.

Layer Normalization normalizes each sample (row) independently, using the mean and
variance computed per sample across all its features.

Key difference: BatchNorm's statistics depend on other samples in the batch (so batch
size matters and it behaves differently at train vs inference time), while LayerNorm's
statistics depend only on the single sample itself - making it batch-size independent
and a common choice for RNNs/Transformers where batch statistics can be unstable.

